import type { Metadata } from "next";
import { Nav } from "./components/Nav";
import { Indie_Flower } from "next/font/google";
import "./globals.css";
import { Footer } from "./components/Footer";

const indieFlower = Indie_Flower({
  variable: "--font-indie-flower",
  subsets: ["latin"],
  weight: ["400"], // Indie Flower only supports 400 weight
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${indieFlower.variable} antialiased`}>
        <Nav />
        <div className="max-w-screen-lg mx-auto p-4 font-[family-name:var(--font-geist-sans)]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
